services:
  history:
    image: ruby:3.3.4-slim-bookworm
    container_name: history-dev
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
    #  - '../grenander:/grenander'
    working_dir: /app
    command: >
      bash -c "apt update &&
              apt install -y build-essential apt-utils git nodejs pkg-config &&
              cd /app &&
              gem install bundler &&
              bundle install &&
              bundle exec ruby -rbundler/setup -e 'Bundler.load.specs.each(&:full_gem_path)' &&
              bundle exec rails db:migrate &&
              bundle exec rails server -b 0.0.0.0"