FROM ruby:3.3.4-slim-bookworm

# Install dependencies
RUN apt update && apt install -y \
  build-essential \
  apt-utils \
  git \
  nodejs \
  libsqlite3-dev \
  pkg-config \
  && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Copy Gemfile for caching
COPY Gemfile Gemfile.lock ./
RUN bundle install

# Copy the app
COPY . .

# Expose port
EXPOSE 3000

# Default command
CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]
