---
Student Life: https://archives.albany.edu/downloads/z603r494p
Presidents: https://archives.albany.edu/downloads/t148fq620
Administration: https://archives.albany.edu/downloads/3b591h455
Alumni: https://archives.albany.edu/downloads/2v23w1509
Centers & Institutes: https://archives.albany.edu/downloads/zc77sw90x
Academic Colleges, Schools & Departments: https://archives.albany.edu/downloads/0g354n53m
University Names: https://archives.albany.edu/downloads/2n49t518n
Enrollment: https://archives.albany.edu/downloads/3n204517h
Academic Programs: https://archives.albany.edu/downloads/fq978175f
Notable Students: https://archives.albany.edu/downloads/g732dh71p
Buildings & Construction: https://archives.albany.edu/downloads/vq27zv56b
Milne School: https://archives.albany.edu/downloads/t435gd02j
Campus Activism: https://archives.albany.edu/downloads/b8515n434
Educational Opportunity Program: https://archives.albany.edu/downloads/7p88cp79r